cognitoDomain: 'flamencotulsa'
identityProviderName: 'COGNITO'
webDomain: http://localhost:3000
authCallbackUrl: http://localhost:3000
samlLogin: false
cors: true
adminEmail: 'lexi@reflejosflamencos.com'
siteEmail: 'no-reply@flamencotulsa.com'
